' ------------------------------------------------------------------------------
' <auto-generated>
' Este código fue generado por una herramienta.
' Versión de runtime:4.0.30319.42000
' 
' Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
' se vuelve a generar el código.
' </auto-generated>
' ------------------------------------------------------------------------------


Imports System.Diagnostics
Imports Microsoft.VisualBasic

Namespace ReviewsJuegos.My.Resources

    ' StronglyTypedResourceBuilder generó automáticamente esta clase
    ' a través de una herramienta como ResGen o Visual Studio.
    ' Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    ' con la opción /str o recompile su proyecto de VS.
    ''' <summary>
    ''' Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    ''' </summary>
    <CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")>
    <DebuggerNonUserCode()>
    <CompilerGenerated()>
    <HideModuleName()>
    Friend Module Resources

        Private resourceMan As System.Resources.ResourceManager

        Private resourceCulture As CultureInfo

        ''' <summary>
        ''' Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        ''' </summary>
        <ComponentModel.EditorBrowsable(ComponentModel.EditorBrowsableState.Advanced)>
        Friend ReadOnly Property ResourceManager As System.Resources.ResourceManager
            Get
                If ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp = New System.Resources.ResourceManager("ReviewsJuegos.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        ''' <summary>
        ''' Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ''' búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        ''' </summary>
        <ComponentModel.EditorBrowsable(ComponentModel.EditorBrowsableState.Advanced)>
        Friend Property Culture As CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(value As CultureInfo)
                resourceCulture = value
            End Set
        End Property
    End Module
End Namespace
