' ------------------------------------------------------------------------------
' <auto-generated>
' Este código fue generado por una herramienta.
' Versión de runtime:4.0.30319.42000
' 
' Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
' se vuelve a generar el código.
' </auto-generated>
' ------------------------------------------------------------------------------

Imports System.Diagnostics
Imports System.Windows.Forms

Namespace ReviewsJuegos.My

    ' NOTA: Este archivo se genera automáticamente; no lo modifique directamente.  Para hacer cambios,
    ' o si detecta errores de compilación en este archivo, vaya al Diseñador de proyectos
    ' (vaya a Propiedades del proyecto o haga doble clic en el nodo My Project en el
    ' Explorador de soluciones) y realice cambios en la pestaña Aplicación.
    ' 
    Friend Partial Class MyApplication

        <DebuggerStepThrough()>
        Public Sub New()
            MyBase.New(ApplicationServices.AuthenticationMode.Windows)
            IsSingleInstance = False
            EnableVisualStyles = True
            SaveMySettingsOnExit = True
            ShutdownStyle = ApplicationServices.ShutdownMode.AfterMainFormCloses
            HighDpiMode = HighDpiMode.DpiUnaware
        End Sub

        <DebuggerStepThrough()>
        Protected Overrides Sub OnCreateMainForm()
            MainForm = Forms.Login
        End Sub
    End Class
End Namespace
